### ISSUE TITLE
获取秒杀初始化信息异常

### ISSUE THREAD

**Issue by linsage** [GumpCode/jd_maotai#2]
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    start_tool.submit_seckill_order()
  File "/Users/linsage/dev/workspace/jd_maotai/jd_mask_spider_requests.py", line 237, in submit_seckill_order
    self.seckill_order_data[self.sku_id] = self._get_seckill_order_data(
  File "/Users/linsage/dev/workspace/jd_maotai/jd_mask_spider_requests.py", line 187, in _get_seckill_order_data
    self.seckill_init_info[self.sku_id] = self._get_seckill_init_info()
  File "/Users/linsage/dev/workspace/jd_maotai/jd_mask_spider_requests.py", line 179, in _get_seckill_init_info
    return parse_json(resp.text)
  File "/Users/linsage/dev/workspace/jd_maotai/util.py", line 63, in parse_json
    return json.loads(s[begin:end])
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by zhangyi2099** [comment]
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    start_tool.make_reserve()
  File "/mnt/d/jd_maotai-master/jd_maotai-master/jd_mask_spider_requests.py", line 61, in make_reserve
    resp_json = parse_json(resp.text)
  File "/mnt/d/jd_maotai-master/jd_maotai-master/util.py", line 63, in parse_json
    return json.loads(s[begin:end])
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
同样问题，ubuntu 20.04，python3.8

**Comment by GumpCode** [comment]
@zhangyi2099 @linsage 请问你们按照首页配置了参数吗

**Comment by linsage** [comment]
eid、fp、cookies_String（从pc端抓取） 都配置了，能预约成功，但是秒杀时会出现上述异常， 环境 Mac，python 3.7.7

@GumpCode

**Comment by GumpCode** [comment]
是只有秒杀瞬间出现异常，还是过了十点会出现没货？如果只是秒杀瞬间异常，那就是挤不进去，可以采用try except的方式反复请求。
如果需要提供成功率，建议使用低时延网络

**Comment by linsage** [comment]
只有秒杀瞬间出现异常，我多留意一下：）

**Comment by zhangyi2099** [comment]
我是预约的时候就出现这个错误，登录可以成功登录，_JdTdudfp这个变量我这里一直没有数据，eid是_Jdeid，fp是_JdJrTdRiskFpInfo这里取的，不知道是不是这里弄错了？

**Comment by zhangyi2099** [comment]
找到原因了，就是sku_id的那个注释

**Comment by KwanTai** [comment]
> 只有秒杀瞬间出现异常，我多留意一下：）



> eid，fp，cookies_String（从pc端抓取）都配置了，能预约成功，但是秒杀时会出现上述异常，环境Mac，python 3.7.7
> 
> @GumpCode

您好：我也出现这个问题，请问解决了吗。
